### ISSUE TITLE
Is it possible to pass "context" options (like lang) on the new Query Builder?

### ISSUE THREAD

**Issue by Wilders** [Ang3/php-odoo-api-client#12]
Hi,

I'm trying to adapt my old code to the new Query Builder.
I was adding :
`'context' => ['lang' => 'fr_FR']]`
as option to my old requests.

I did not found the possibility to select the language in the Query Builder, I think this could be a nice improvement if it doesn't exists actually.

Thanks !

**Comment by Ang3** [comment]
Hello,

Thank you for your feedback.

Initially, the query builder has been developed for DBAL features. That's why it is not possible at right now.
However, you could get the query from the query builder, then replace options directly to the query so as to add your context parameters.

I put the label "enchancement" for this issue to add a query builder feature for query extra options. ;)

**Comment by Wilders** [comment]
Hi,
Doing things like that replace all options (like select,etc..)

Example : 
```php
$rm = new RecordManager(Auth::client());
            $order = $rm
                ->createQueryBuilder('mrp.production')
                ->select(['id', 'move_raw_ids'])
                ->getQuery()
                ->setOptions(["context" => ["lang" => "fr_FR"]])
                ->getOneOrNullResult();
```
This request will fetch every fields and not only the selected ones, because setOptions overrides all options.
I suggest adding an addOption method that add the option to the array of options.
